### ISSUE TITLE
Création de routine  : l'ajout d'un groupe semble déclencher createWorkout()

### ISSUE THREAD

**Issue by Drainman** [Polytech-Paris-Sud-Web/Progressive-Workout-App#10]
Reproduction du Bug : 

- Allez sur la page de création de routine/workout 
- Appuyez sur "New Group"
- Constater que la fonction createWorkout a été lancé (message SweetAlert)

**Comment by Drainman** [comment]
Note : Je pense que l'ano qui produisait trois routines dans la liste vient d'ici aussi :)

**Comment by Grimnir777** [comment]
ça a été corrigé par mes derniers commit mais j'ai pas merge encore
